netbox_sd_access/urls.py
from django.urls import path
from netbox.views.generic import ObjectChangeLogView

from . import models, views
"Assigns urls to access different views"

urlpatterns = (
    path("fabric-sites/", views.FabricSiteListView.as_view(), name='fabricsite_list'),
    path("fabric-sites/add/", views.FabricSiteEditView.as_view(), name='fabricsite_add'),
    path('fabric-sites/import/', views.FabricSiteImportView.as_view(), name='fabricsite_import'),
    path('fabric-sites/delete/', views.FabricSiteBulkDeleteView.as_view(), name='fabricsite_bulk_delete'),
    path('fabric-sites/<int:pk>/', views.FabricSiteView.as_view(), name='fabricsite'),
    path('fabric-sites/<int:pk>/edit/', views.FabricSiteEditView.as_view(), name='fabricsite_edit'),
    path('fabric-sites/<int:pk>/delete/', views.FabricSiteDeleteView.as_view(), name='fabricsite_delete'),
    path('fabric-sites/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='fabricsite_changelog', 
         kwargs={'model': models.FabricSite}),

    #####Virtual Networks
    path("virtual-networks/", views.VirtualNetworkListView.as_view(), name='virtualnetwork_list'),
    path("virtual-networks/add/", views.VirtualNetworkEditView.as_view(), name='virtualnetwork_add'),
    path("virtual-networks/import/", views.VirtualNetworkImportView.as_view(), name='virtualnetwork_import'),
    path("virtual-networks/delete/", views.VirtualNetworkBulkDeleteView.as_view(), name='virtualnetwork_bulk_delete'),
    path('virtual-networks/<int:pk>/', views.VirtualNetworkView.as_view(), name='virtualnetwork'),
    path("virtual-networks/<int:pk>/edit/", views.VirtualNetworkEditView.as_view(), name='virtualnetwork_edit'),
    path('virtual-networks/<int:pk>/delete/', views.VirtualNetworkDeleteView.as_view(), name = "virtualnetwork_delete"),
    path('virtual-networks/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='virtualnetwork_changelog',
         kwargs={'model': models.VirtualNetwork}),
    
    #### TRANSITS
    path("ip-transits/", views.IPTransitListView.as_view(), name='iptransit_list'),
    path("ip-transits/add/", views.IPTransitEditView.as_view(), name='iptransit_add'),
    path('ip-transits/<int:pk>/', views.IPTransitView.as_view(), name='iptransit'),
    path('ip-transits/<int:pk>/edit/', views.IPTransitEditView.as_view(), name='iptransit_edit'),
    path('ip-transits/<int:pk>/delete/', views.IPTransitDeleteView.as_view(), name='iptransit_delete'),
    path('ip-transits/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='iptransit_changelog', 
         kwargs={'model': models.IPTransit}),
    path('ip-transits/import/', views.IPTransitBulkImportView.as_view(), name='iptransit_import'),
    path('ip-transits/delete/', views.IPTransitBulkDeleteView.as_view(), name='iptransit_bulk_delete'),
        
    path("sda-transits/", views.SDATransitListView.as_view(), name='sdatransit_list'),
    path("sda-transits/add/", views.SDATransitEditView.as_view(), name='sdatransit_add'),
    path('sda-transits/<int:pk>/', views.SDATransitView.as_view(), name='sdatransit'),
    path('sda-transits/<int:pk>/edit/', views.SDATransitEditView.as_view(), name='sdatransit_edit'),
    path('sda-transits/<int:pk>/delete/', views.SDATransitDeleteView.as_view(), name='sdatransit_delete'),
    path('sda-transits/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='sdatransit_changelog', 
         kwargs={'model': models.SDATransit}),
    path('sda-transits/import/', views.SDATransitBulkImportView.as_view(), name='sdatransit_import'),
    path('sda-transits/delete/', views.SDATransitBulkDeleteView.as_view(), name='sdatransit_bulk_delete'),
    
    #### SDA Devices
    path("sda-devices/", views.SDADeviceListView.as_view(), name='sdadevice_list'),
    path("sda-devices/add/", views.SDADeviceEditView.as_view(), name='sdadevice_add'),
    path('sda-devices/import/', views.SDADeviceBulkImportView.as_view(), name='sdadevice_import'),
    path('sda-device/delete/', views.SDADeviceBulkDeleteView.as_view(), name='sdadevice_bulk_delete'),
    path('sda-devices/<int:pk>/', views.SDADeviceView.as_view(), name='sdadevice'),
    path('sda-devices/<int:pk>/edit/', views.SDADeviceEditView.as_view(), name='sdadevice_edit'),
    path('sda-devices/<int:pk>/delete/', views.SDADeviceDeleteView.as_view(), name='sdadevice_delete'),
    path('sda-devices/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='sdadevice_changelog', 
         kwargs={'model': models.SDADevice}),

    #### IP Pools
    path("ip-pools/", views.IPPoolListView.as_view(), name='ippool_list'),
    path("ip-pools/add/", views.IPPoolEditView.as_view(), name='ippool_add'),
    path("ip-pools/import/", views.IPPoolBulkImportView.as_view(), name='ippool_import'),
    path('ip-pools/delete/', views.IPPoolBulkDeleteView.as_view(), name='ippool_bulk_delete'),
    path('ip-pools/<int:pk>/', views.IPPoolView.as_view(), name='ippool'),
    path('ip-pools/<int:pk>/edit/', views.IPPoolEditView.as_view(), name='ippool_edit'),
    path('ip-pools/<int:pk>/delete/', views.IPPoolDeleteView.as_view(), name='ippool_delete'),
    path('ip-pools/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='ippool_changelog', 
         kwargs={'model': models.IPPool}),
)

netbox_sd_access/models.py
from django.db import models
from django.urls import reverse
from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet
from django.core.exceptions import ValidationError

import netaddr

"""
Each model class represents an underlying PostreSQL database. Each instance of the 
model is a row in the database.
"""

class IPPool(NetBoxModel):
    """
    IP Pool model groups existing IP prefix, gateway, DHCP, and DNS server. IP pools are associated with a given fabric site.
    """
    name = models.CharField(max_length=200)
    prefix = models.ForeignKey(to='ipam.Prefix', on_delete=models.PROTECT)
    gateway = models.ForeignKey(to='ipam.IPAddress', on_delete=models.PROTECT)
    dhcp_server = models.ForeignKey(to='ipam.IPAddress', on_delete=models.PROTECT, related_name='dhcp_server')
    dns_servers = models.ManyToManyField(to='ipam.IPAddress', related_name='dns_servers')
    comments = models.TextField(blank=True)
    
    class Meta:
        ordering = ("name",)
        verbose_name = 'IP Pool'
        verbose_name_plural = 'IP Pools'
        constraints = (
            models.UniqueConstraint(
                fields=('name',),
                name='netbox_sd_access_ip_pool_unique_name'
            ),
        )
    
    def get_absolute_url(self):
        return reverse("plugins:netbox_sd_access:ippool", args=[self.pk])
    
    def __str__(self) -> str:
        return self.name
    
    def clean(self):
        """
        Verify that the gateway is in the same subnet as the prefix.
        """
        if netaddr.IPNetwork(self.gateway.address) != self.prefix.prefix:
            raise ValidationError('Gateway must be in the same subnet as prefix.')

    
class FabricSite(NetBoxModel):
    """
    All SD-Access features can be associated with a fabric site. 
    """
    name = models.CharField(max_length=200)
    physical_site = models.ForeignKey(to='dcim.Site', on_delete=models.PROTECT)
    # locations is an optional field for if you make the fabric on a per floor basis
    location = models.OneToOneField(to='dcim.Location', on_delete=models.PROTECT, blank=True, null=True)
    ip_prefixes = models.ManyToManyField(to=IPPool)
    comments = models.TextField(blank=True)
    
    class Meta:
        ordering = ("name",)
        constraints = (
            models.UniqueConstraint(
                fields=('name',),
                name='netbox_sd_access_fabric_site_unique_name'
            ),
        )
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_sd_access:fabricsite', args=[self.pk])


class SDADeviceRoleChoices(ChoiceSet):
    """
    Set possible SD device roles
    """
    CHOICES = [
        ('control', 'Control Plane Node', 'blue'),
        ('edge', 'Edge Node', 'red'),
        ('external-border', 'External Border Node', 'yellow'),
        ('internal-border', 'Internal Border Node', 'green'),
        ('l2-border', 'L2 Border Node', 'teal')
    ]
    


class SDATransitTypeChoices(ChoiceSet):
    """
    Set possible SD Transit types
    """
    CHOICES = [
        ('lisp', 'LISP', 'yellow'),
        ('lisp-bgp', 'LISP-BGP', 'green')
    ]
    
class SDADevice(NetBoxModel):
    """
    SD Device assigns existing Netbox device to one of a given set of roles and a Fabric Site. 
    """
    device = models.OneToOneField(to='dcim.Device', on_delete=models.CASCADE, related_name='sda_info')
    role = models.CharField(max_length=50, choices=SDADeviceRoleChoices, blank=True, null=True)
    fabric_site = models.ForeignKey(to=FabricSite, on_delete=models.CASCADE, related_name='devices')
    comments = models.TextField(blank=True)
    
    class Meta:
        ordering = ('fabric_site','device',)
        verbose_name = 'SDA Device'
        verbose_name_plural = 'SDA Devices'
    
    def __str__(self):
        return self.device.name

    def get_absolute_url(self):
        return reverse("plugins:netbox_sd_access:sdadevice", args=[self.pk])
    
    def get_role_color(self):
        return SDADeviceRoleChoices.colors.get(self.role)
    
    def clean(self):
        """
        Fabric site and device must belong to the same site
        """
        if (self.fabric_site.physical_site != self.device.site):
            raise ValidationError('Fabric site and device must belong to the same site and location')
        
        if (self.fabric_site.location):
            device_location = self.device.location
            
            while device_location and device_location != self.fabric_site.location:
                device_location = device_location.parent
            
            if not device_location:
                raise ValidationError('Fabric site and device must belong to the same site and location')
            
    
class SDATransit(NetBoxModel):
    """
    Transit between site and outside network
    """
    name=models.CharField(max_length=200)
    transit_type=models.CharField(max_length=8, choices=SDATransitTypeChoices, default=SDATransitTypeChoices.CHOICES[0], blank=False, null=False)
    fabric_site=models.OneToOneField(to=FabricSite, on_delete=models.PROTECT, blank=True, null=True)
    control_plane_node=models.OneToOneField(to=SDADevice, on_delete=models.PROTECT, blank=False, related_name="transit_control_nodes")
    devices=models.ManyToManyField(to=SDADevice, blank=True, related_name="transit_devices")
    comments=models.TextField(blank=True)
    
    class Meta:
        ordering = ("name",)
        verbose_name = "SDA Transit"
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_sd_access:sdatransit', args=[self.pk])
    
    def get_role_color(self):
        return SDATransitTypeChoices.colors.get(self.role)
    

class IPTransit(NetBoxModel):
    """
    Transit between site and outside network using BGP. Applys existing ASN configuration to SDA transit.
    """
    name=models.CharField(max_length=200)
    fabric_site=models.OneToOneField(to=FabricSite, on_delete=models.PROTECT, blank=True, null=True)
    asn=models.OneToOneField(to='ipam.ASN',on_delete=models.PROTECT,null=True, blank=True)
    comments=models.TextField(blank=True)
    
    class Meta:
        ordering = ("name",)
        verbose_name = "IP Transit"
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_sd_access:iptransit', args=[self.pk])


class VirtualNetwork(NetBoxModel):
    """
    Virtual Network is VRF for SD-Access. Can contain multiple fabric sites.
    """
    name=models.CharField(max_length=200, default = "Virtual Network")
    fabric_site=models.ManyToManyField(to=FabricSite, blank= True,related_name = 'virtual_networks')
    vrf=models.OneToOneField(to='ipam.VRF', on_delete = models.PROTECT)

    class Meta:
        ordering = ("name",)
        constraints = (
            models.UniqueConstraint(
                fields=('name',),
                name='netbox_sd_access_vns_unique_name',
            ),
        )
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_sd_access:virtualnetwork', args=[self.pk])

netbox_sd_access/templates/netbox_sd_access/fabricsite.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Fabric Site</h5>
            <div class="card-body"><table class="table table-hover attr-table"><tr>
                <th scope="row">Name</th>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <th scope="row">Physical Site</th>
                <td><a href="{{ object.physical_site.get_absolute_url }}">{{ object.physical_site }}</a></td>
            </tr>
            <tr>
                <th scope="row">Location</th>
                <td><a href="{{ object.location.get_absolute_url }}">{{ object.location }}</a></td>
            </tr>
            <tr>
                <th scope="row">Number of Devices</th>
                <td>{{ object.devices.count }}</td>
            </tr>
            <tr>
                <th scope="row">IP Pools</th>
                <td>{% for prefix in object.ip_prefixes.all %}
                    <a href="{{ prefix.get_absolute_url }}">{{ prefix.prefix }}</a>
                    <br>
                    {% endfor %}
                </td>
            </tr></table></div>
        </div>
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
        <div class="card">
            <h5 class="card-header">Devices</h5>
            <div class="card-body table-responsive">
                {% render_table devices_table %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/ip_transit.html
{% extends 'generic/object.html' %} {% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Fabric Site</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">Name</th>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Fabric Site</th>
                        <td>
                            <a href="{{ object.fabric_site.get_absolute_url }}"
                                >{{ object.fabric_site }}</a
                            >
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">ASN</th>
                        <td>{{ object.asn }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/ippool.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">IP Pool</h5>
            <div class="card-body"><table class="table table-hover attr-table"><tr>
                <th scope="row">Name</th>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <th scope="row">Prefix</th>
                <td><a href="{{ object.prefix.get_absolute_url }}">{{ object.prefix }}</a></td>
            </tr>
            <tr>
                <th scope="row">Gateway</th>
                <td><a href="{{ object.gateway.get_absolute_url }}">{{ object.gateway }}</a></td>
            </tr>
            <tr>
                <th scope="row">DHCP Server</th>
                <td><a href="{{ object.dhcp_server.get_absolute_url }}">{{ object.dhcp_server }}</a></td>
            </tr>
            <tr>
                <th scope="row">DNS Servers</th>
                <td>{% for server in object.dns_servers.all %}
                    <a href="{{ server.get_absolute_url }}">{{ server }}</a>
                    <br>
                    {% endfor %}
                </td>
            </tr></table></div>
        </div>
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
    </div>
</div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/iptransit.html
{% extends 'generic/object.html' %} 
{% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Fabric Site</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">Name</th>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Fabric Site</th>
                        <td>
                            <a href="{{ object.fabric_site.get_absolute_url }}"
                                >{{ object.fabric_site }}</a
                            >
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">ASN</th>
                        <td>
                        <a href="{{ object.asn.get_absolute_url }}" 
                        >{{ object.asn }}</a>   
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
    </div>
</div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/sdadevice.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">

        <h5 class="card-header">SDA Device</h5>

        <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td><a href="{{ object.device.get_absolute_url }}">{{ object.device }}</a></td>
            </tr>
            <tr>
              <th scope="row">Fabric Site</th>
              <td><a href="{{ object.fabric_site.get_absolute_url }}">{{ object.fabric_site }}</a></td>
            </tr>
            <tr>
              <th scope="row">Role</th>
              <td>{% badge object.get_role_display bg_color=object.get_role_color %}</td>
            </tr>
        </table>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
    </div>
  </div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/sdatransit.html
{% extends 'generic/object.html' %} 
{% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Fabric Site</h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <th scope="row">Name</th>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Transit Type</th>
                        <td>{{ object.transit_type }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Fabric Site</th>
                        <td>
                            <a href="{{ object.fabric_site.get_absolute_url }}"
                                >{{ object.fabric_site }}</a
                            >
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Control Plane Node</th>
                        <td>
                            <a href="{{ object.control_plane_node.get_absolute_url }}"
                                >{{ object.control_plane_node }}</a
                            >
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Number of Devices</th>
                        <td>{{ object.devices.count }}</td>
                    </tr>
                </table>
            </div>
        </div>
        {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
        <div class="card">
            <h5 class="card-header">Devices</h5>
            <div class="card-body table-responsive">
                {% render_table devices_table %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

netbox_sd_access/templates/netbox_sd_access/virtualnetwork.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="row mb-3">
    <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">Virtual Network</h5>
            <div class="card-body"><table class="table table-hover attr-table"><tr>
                <th scope="row">Name</th>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <th scope="row">VRF</th>
                <td><a href="{{ object.vrf.get_absolute_url }}">{{ object.vrf }}</a></td>
            </tr>
            <tr>
                <th scope="row">Fabric Sites</th>
                <td>{% for site in object.fabric_site.all %}
                    <a href="{{ site.get_absolute_url }}">{{ site }}</a>
                    <br>
                    {% endfor %}
                </td>
            </tr>
            </table>
        </div>
    </div>
</div>
{% endblock content %}